version: '2'
services:
    web:
        build:
            context: .
            args:
                - http_proxy
                - https_proxy
                - no_proxy
        ports:
            - "5000:5000"
        volumes:
            - ../../:/skyplanner
            - ./entrypoint:/entrypoint
        environment:
            - FLASK_DEBUG=${FLASK_DEBUG}
            - http_proxy=${http_proxy}
            - https_proxy=${https_proxy}
            - no_proxy=${no_proxy}

