version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - ../../:/skyplanner
            - ./entrypoint:/entrypoint
        environment:
            - FLASK_DEBUG=${FLASK_DEBUG}

