#!/bin/bash
source "$HOME/.profile"
#export LC_ALL=C.UTF-8
#export LANG=C.UTF-8

setup() {
    if ! grep -q '# entrypoint setup' "$HOME/.bashrc"; then
        echo "# entrypoint setup" >> "$HOME/.bashrc"
        echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$HOME/.bashrc"
    fi
    pip3 install --user -r requirements.txt
    npm install
    #bower install
    (
        cd skyplanner/ephemeris/native
    #    rm *.so build -rf
        python3 setup.py build_ext --inplace
    )
    (
        while true; do
            gulp watch
            while ! gulp transform >/dev/null 2>&1; do
                sleep 1
            done
        done
    ) &
}

case "$1" in
    'shell')
        flask shell
        ;;
    *)
        setup
        flask run --host=0.0.0.0 
        ;;
esac
