set(AAPLUS_SRCS
${CMAKE_SOURCE_DIR}/src/aaplus/AAAberration.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AAAngularSeparation.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AABinaryStar.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AACoordinateTransformation.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AADate.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AADiameters.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AADynamicalTime.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AAEarth.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AAEaster.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AAEclipses.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AAEclipticalElements.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AAElementsPlanetaryOrbit.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AAElliptical.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AAEquationOfTime.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AAEquinoxesAndSolstices.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AAFK5.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AAGalileanMoons.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AAGlobe.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AAIlluminatedFraction.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AAInterpolate.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AAJewishCalendar.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AAJupiter.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AAKepler.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AAMars.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AAMercury.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AAMoonIlluminatedFraction.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AAMoonMaxDeclinations.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AAMoonNodes.cpp
${CMAKE_SOURCE_DIR}/src/aaplus/AAMoonPerigeeApogee.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AAMoonPhases.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AAMoslemCalendar.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AANeptune.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AANodes.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AANutation.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AAParabolic.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AAParallactic.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AAParallax.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AAPhysicalJupiter.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AAPhysicalMars.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AAPhysicalMoon.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AAPhysicalSun.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AAPlanetaryPhenomena.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AAPlanetPerihelionAphelion.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AAPluto.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AAPrecession.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AARefraction.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AARiseTransitSet.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AASaturn.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AASaturnMoons.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AASaturnRings.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AASidereal.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AAStellarMagnitudes.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AASun.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AAUranus.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AAVenus.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/stdafx.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AANearParabolic.cpp 
${CMAKE_SOURCE_DIR}/src/aaplus/AAMoon.cpp
)

