#!/bin/bash
TEMPLATE="$1"
CSS="$2"
OUTPUT="$3"

if ! [ -r "$OUTPUT" ] || [ "$CSS" -nt "$OUTPUT" ]; then
  awk "/#ifndef/,/\/\* STYLE_CSS_CONTENT \*\//" "$TEMPLATE" > "$OUTPUT"
  cat "$CSS" >> "$OUTPUT"
  awk '/\/\* STYLE_CSS_CONTENT \*\//,/#endif/' "$TEMPLATE" >> "$OUTPUT"
fi


