version: '2'
volumes:
  data:
  postgres:
  build:

services:
    postgres:
      image: postgres:latest
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "skyplanner"
        POSTGRES_DB: "skyplanner"
      volumes:
        - postgres:/var/lib/postgresql/data

    app:
      build: skyplanner
      environment:
        MAKEOPTS: '${MAKEOPTS}'
        SKYPLANNER_PSQL_CONNECTION: "application_name=SkyPlanner host=postgres port=5432 dbname=skyplanner user=postgres password=skyplanner"
        SKYPLANNER_DSS_CACHE_DIR: "/data/dss"
        SKYPLANNER_DSSCACHE_DEPLOY_PATH: "${SKYPLANNER_DSSCACHE_DEPLOY_PATH}"
      volumes:
          - ../../:/SkyPlanner:ro
          - data:/data
          - build:/SkyPlanner-build
      ports:
        - "${SKYPLANNER_PORT}:8080"
      depends_on:
        - postgres
        - smtp
    smtp:
      image: namshi/smtp
      environment:
        MAILNAME: '${SKYPLANNER_DOMAIN_NAME}'
