version: '2'
volumes:
  data:
  postgres:
  build:

services:
    postgres:
      image: postgres:latest
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "skyplanner"
        POSTGRES_DB: "skyplanner"
      volumes:
        - postgres:/var/lib/postgresql/data

    app:
      build: skyplanner
      environment:
        MAKEOPTS: '${MAKEOPTS}'
        SKYPLANNER_PSQL_CONNECTION: "application_name=SkyPlanner host=postgres port=5432 dbname=skyplanner user=postgres password=skyplanner"
        SKYPLANNER_DSS_CACHE_DIR: "/data/dss"
        SKYPLANNER_DSSCACHE_DEPLOY_PATH: "${SKYPLANNER_DSSCACHE_DEPLOY_PATH}"
      volumes:
          - ../../:/SkyPlanner:ro
          - data:/data
          - build:/SkyPlanner-build
      ports:
        - "${SKYPLANNER_PORT}:8080"
      depends_on:
        - postgres
        - smtp
    smtp:
      build: smtp
      environment:
        MAILNAME: '${SKYPLANNER_SMTP_MAILNAME}'
        GMAIL_USER: '${SKYPLANNER_SMTP_GMAIL_USER}'
        GMAIL_PASSWORD: '${SKYPLANNER_SMTP_GMAIL_PASSWORD}'
        RELAY_DOMAINS: '${SKYPLANNER_SMTP_RELAY_DOMAINS}'
        SES_USER: '${SKYPLANNER_SMTP_SES_USER}'
        SES_PASSWORD: '${SKYPLANNER_SMTP_SES_PASSWORD}'
        SMARTHOST_ADDRESS: '${SKYPLANNER_SMTP_SMARTHOST_ADDRESS}'
        SMARTHOST_PORT: '${SKYPLANNER_SMTP_SMARTHOST_PORT}'
        SMARTHOST_USER: '${SKYPLANNER_SMTP_SMARTHOST_USER}'
        SMARTHOST_PASSWORD: '${SKYPLANNER_SMTP_SMARTHOST_PASSWORD}'
        SMARTHOST_ALIASES: '${SKYPLANNER_SMTP_SMARTHOST_ALIASES}'
        
