#!/bin/bash
if [[ "$COPY_STATIC_FILES" == "true" ]]; then
  echo "Copying static files for external http daemon caching in $STATIC_FILES_CACHE_PATH"
  cp -av "$STATIC_FILES_PATH"/* "$STATIC_FILES_CACHE_PATH"
fi
/usr/bin/SkyPlanner "$@"